### ISSUE TITLE
Create token processor that converts tokens into object heirarchy

### ISSUE THREAD

**Issue by aamironline** [maniartech/internet-object#1]
Converts tokens `One, Two, Three, { A, B, C}, [T, F]` into the following hierarchy

```js
{
  type: 'object',
  values: [
    'One', 'Two', 'Three', {
      type: 'object',
      values: ['A', 'B', 'C']
    }, {
      type: 'array',
      values: ['T', 'F']
    }
  ]
}
```

**Comment by harenlewis** [comment]
Working on it!

**Comment by aamironline** [comment]
@harenlewis Pull the latest and see if that helps you!

**Comment by aamironline** [comment]
The parser now generates the following kind of hierarchy!

![image](https://user-images.githubusercontent.com/134134/52520563-83d1fa80-2c90-11e9-8e85-106023a4acaf.png)
